server.port=8086
spring.application.name=expense-service
spring.datasource.url=jdbc:postgresql://localhost:5432/vouch_expenses
spring.datasource.username=postgres
spring.datasource.password=bully
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=vouch-super-secret-key-that-should-be-at-least-256-bits-long-for-security-purposes-change-this-in-production
services.auth-service.url=http://localhost:8081
services.notification-service.url=http://localhost:8082
