# ========================
# SERVER
# ========================
server.port=8084
spring.application.name=payment-service

# ========================
# DATABASE (dedicated payments database)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/vouch_payments
spring.datasource.username=postgres
spring.datasource.password=bully
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# JWT (same secret as auth-service for token validation)
# ========================
jwt.secret=vouch-super-secret-key-that-should-be-at-least-256-bits-long-for-security-purposes-change-this-in-production

# ========================
# PAYSTACK
# ========================
paystack.secret.key=sk_test_f8314ab6417b564aff03567f2d8779117da281d7
paystack.callback.url=http://localhost:8084/api/payments/callback

# ========================
# SERVICE URLS
# ========================
services.auth-service.url=http://localhost:8081
services.loan-service.url=http://localhost:8083
services.notification-service.url=http://localhost:8082
