# ========================
# SERVER
# ========================
server.port=8080

# ========================
# DATABASE
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/vouch
spring.datasource.username=postgres
spring.datasource.password=bully
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# JWT
# ========================
jwt.secret=vouch-super-secret-key-that-should-be-at-least-256-bits-long-for-security-purposes-change-this-in-production
jwt.expiration=86400000
paystack.secret.key=sk_test_f8314ab6417b564aff03567f2d8779117da281d7